version: '3'

networks:
  quinn-perf:
    ipam:
      config:
        - subnet: 172.42.0.0/16

services:
  server:
    build: .
    image: quinn_perf
    networks:
      quinn-perf:
        ipv4_address: 172.42.0.2
    volumes:
      - ./work:/root/.local/share/quinn
    cap_add:
      - NET_ADMIN
    environment:
      - SSLKEYLOGFILE=/root/.local/share/quinn/server.key

  client:
    image: quinn_perf
    networks:
      quinn-perf:
        ipv4_address: 172.42.0.3
    volumes:
      - ./work:/root/.local/share/quinn
    cap_add:
      - NET_ADMIN
    environment:
      - SSLKEYLOGFILE=/root/.local/share/quinn/client.key
